version: "3.8"
services:
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    container_name: paathshala-backend
    env_file: ./backend/.env
    ports:
      - "8000:8000"
    restart: always

  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    container_name: paathshala-frontend
    env_file: ./frontend/.env
    environment:
      REACT_APP_BACKEND_URL: "http://localhost:8000"
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: always
